// Authentication API
// Updated to match Propella Django Backend API specification

import apiClient from "./client";
import { ENDPOINTS } from "@/config/endpoints";
import { getReferralData, clearReferralData } from "@/utils/referral";

// Cookie helper for cross-subdomain token reading
const getCookie = (name: string): string | null => {
  if (typeof document === "undefined") return null;
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) {
    return parts.pop()?.split(";").shift() || null;
  }
  return null;
};

// Get auth token (checks cookies first for cross-subdomain, then localStorage)
const getAuthTokenFromCookies = (): string | null => {
  if (typeof window === "undefined") return null;
  // Check cookies first (set by landing page with Domain=.propella.ng)
  const cookieToken = getCookie("access_token") || getCookie("auth_token");
  if (cookieToken) return cookieToken;
  // Fallback to localStorage
  return localStorage.getItem("propella_token") || 
         localStorage.getItem("access_token");
};

export interface LoginPayload {
  email: string;
  password: string;
}

export interface SignupPayload {
  email: string;
  password: string;
  confirm_password?: string;
  username?: string;
  nickname?: string;
  referral_code?: string;      // User's own referral code (generated by backend or client)
  referred_by?: string;        // Referrer's code (if came via referral link)
  referrer_name?: string;
  referrer_email?: string;
}

export interface TokenResponse {
  access: string;
  refresh: string;
}

export interface AuthResponse extends TokenResponse {
  user: {
    id: string;
    email: string;
    username?: string;
    nickname?: string;
    referral_code?: string;    // User's personal referral code from backend
    referral_points?: number;
    total_referrals?: number;
  };
}

export interface VerifyEmailPayload {
  email: string;
  code: string;
}

export interface ForgotPasswordPayload {
  email: string;
}

export interface ResetPasswordPayload {
  new_password: string;
  confirm_password: string;
}

export interface ChangePasswordPayload {
  old_password: string;
  new_password: string;
  confirm_password?: string;
}

// Generate a unique referral code (fallback if backend doesn't provide one)
export function generateReferralCode(): string {
  const prefix = "PROP";
  const suffix = Math.random().toString(36).substring(2, 8).toUpperCase();
  return `${prefix}${suffix}`;
}

export const authApi = {
  // Login using JWT token endpoint (POST /api/accounts/token/)
  login: async (payload: LoginPayload): Promise<TokenResponse> => {
    const response = await apiClient.post(ENDPOINTS.auth.login, payload);
    return response.data;
  },

  // Register new user (POST /api/accounts/register/)
  signup: async (payload: SignupPayload): Promise<AuthResponse> => {
    // Get referral data if exists (from URL params/localStorage)
    // This is the referrer's code - who referred the current user
    const { code, name, email } = getReferralData();
    
    // Generate referral code for new user if not provided
    // This will be the new user's personal referral code
    const userReferralCode = payload.referral_code || generateReferralCode();
    
    // Build payload with referral data
    const signupPayload: SignupPayload = {
      ...payload,
      username: payload.username || payload.nickname || payload.email.split('@')[0],
      referral_code: userReferralCode,  // User's own referral code
      ...(code && { referred_by: code }), // Referrer's code (if came via referral link)
      ...(name && { referrer_name: name }),
      ...(email && { referrer_email: email }),
    };
    
    const response = await apiClient.post(ENDPOINTS.auth.register, signupPayload);
    
    // Clear referral data after successful signup
    if (response.data) {
      clearReferralData();
    }
    
    return response.data;
  },

  // Refresh access token (POST /api/accounts/token/refresh/)
  refresh: async (refreshToken: string): Promise<{ access: string }> => {
    const response = await apiClient.post(ENDPOINTS.auth.refresh, {
      refresh: refreshToken,
    });
    return response.data;
  },

  // Verify email (POST /api/accounts/verify-email/)
  verifyEmail: async (payload: VerifyEmailPayload): Promise<void> => {
    const response = await apiClient.post(ENDPOINTS.auth.verifyEmail, payload);
    return response.data;
  },

  // Resend verification code (POST /api/accounts/resend-code/)
  resendVerificationCode: async (email: string): Promise<void> => {
    const response = await apiClient.post(ENDPOINTS.auth.resendCode, { email });
    return response.data;
  },

  // Forgot password (POST /api/accounts/forgot-password/)
  forgotPassword: async (payload: ForgotPasswordPayload): Promise<void> => {
    const response = await apiClient.post(ENDPOINTS.auth.forgotPassword, payload);
    return response.data;
  },

  // Reset password (POST /api/accounts/reset-password/{uid}/{token}/)
  resetPassword: async (
    uid: string, 
    token: string, 
    payload: ResetPasswordPayload
  ): Promise<void> => {
    const response = await apiClient.post(
      ENDPOINTS.auth.resetPassword(uid, token), 
      payload
    );
    return response.data;
  },

  // Change password (PUT/PATCH /api/accounts/change-password/)
  changePassword: async (payload: ChangePasswordPayload): Promise<void> => {
    const response = await apiClient.put(ENDPOINTS.auth.changePassword, payload);
    return response.data;
  },

  // Logout (client-side only for JWT) - clears both token names
  logout: async (): Promise<void> => {
    localStorage.removeItem("propella_token");
    localStorage.removeItem("access_token");
    localStorage.removeItem("propella_refresh_token");
    localStorage.removeItem("refresh_token");
  },

  // Helper to set token after login (sets both names for compatibility)
  setToken: (token: string): void => {
    localStorage.setItem("propella_token", token);
    localStorage.setItem("access_token", token);
  },

  // Helper to set refresh token (sets both names for compatibility)
  setRefreshToken: (token: string): void => {
    localStorage.setItem("propella_refresh_token", token);
    localStorage.setItem("refresh_token", token);
  },

  // Helper to get token (checks cookies first for cross-subdomain, then localStorage)
  getToken: (): string | null => {
    return getAuthTokenFromCookies();
  },

  // Helper to get refresh token (checks cookies first, then localStorage)
  getRefreshToken: (): string | null => {
    // Check cookies first (set by landing page with Domain=.propella.ng)
    const cookieToken = getCookie("refresh_token");
    if (cookieToken) return cookieToken;
    // Fallback to localStorage
    return localStorage.getItem("propella_refresh_token") ||
           localStorage.getItem("refresh_token");
  },

  // Helper to check if user is authenticated (checks cookies first, then localStorage)
  isAuthenticated: (): boolean => {
    return !!getAuthTokenFromCookies();
  },
};
