// Authentication API
// Updated to match Propella Django Backend API specification

import apiClient from "./client";
import { ENDPOINTS } from "@/config/endpoints";
import { getReferralData, clearReferralData } from "@/utils/referral";

// Cookie helper for cross-subdomain token reading
const getCookie = (name: string): string | null => {
  if (typeof document === "undefined") return null;
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) {
    return parts.pop()?.split(";").shift() || null;
  }
  return null;
};

// Access token: cookie is source of truth (24h); when cookie missing, treat as logged out
const getAuthTokenFromCookies = (): string | null => {
  if (typeof window === "undefined") return null;
  const cookieToken = getCookie("access_token") || getCookie("auth_token");
  if (cookieToken) return cookieToken;
  localStorage.removeItem("propella_token");
  localStorage.removeItem("access_token");
  return null;
};

// User + session storage (localStorage is effective; 24h TTL matches access token)
const STORAGE_KEY_USER = "propella_user";
const STORAGE_KEY_EXPIRY = "propella_session_expiry";
const TOKEN_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

export interface StoredUser {
  id: number;
  email: string;
  username?: string;
  nickname?: string;
}

function getStoredUserInternal(): StoredUser | null {
  if (typeof window === "undefined") return null;
  try {
    const expiryRaw = localStorage.getItem(STORAGE_KEY_EXPIRY);
    const userRaw = localStorage.getItem(STORAGE_KEY_USER);
    if (!expiryRaw || !userRaw) return null;
    const expiry = Number(expiryRaw);
    if (Number.isNaN(expiry) || expiry < Date.now()) {
      localStorage.removeItem(STORAGE_KEY_USER);
      localStorage.removeItem(STORAGE_KEY_EXPIRY);
      return null;
    }
    return JSON.parse(userRaw) as StoredUser;
  } catch {
    return null;
  }
}

function clearUserStorage(): void {
  if (typeof window === "undefined") return;
  localStorage.removeItem(STORAGE_KEY_USER);
  localStorage.removeItem(STORAGE_KEY_EXPIRY);
}

export interface LoginPayload {
  email: string;
  password: string;
}

export interface SignupPayload {
  email: string;
  password: string;
  confirm_password?: string;
  username?: string;
  nickname?: string;
  referral_code?: string;      // User's own referral code (generated by backend or client)
  referred_by?: string;        // Referrer's code (if came via referral link)
  referrer_name?: string;
  referrer_email?: string;
}

export interface TokenResponse {
  access: string;
  refresh: string;
}

/** Login API response: { success, message, data: { access, refresh, user } } */
export interface LoginApiResponse {
  success: boolean;
  message: string;
  data: {
    access: string;
    refresh: string;
    user: {
      id: number;
      email: string;
      username?: string;
      nickname?: string;
    };
  };
}

export interface AuthResponse extends TokenResponse {
  user: {
    id: string;
    email: string;
    username?: string;
    nickname?: string;
    referral_code?: string;    // User's personal referral code from backend
    referral_points?: number;
    total_referrals?: number;
  };
}

export interface VerifyEmailPayload {
  email: string;
  code: string;
}

export interface ForgotPasswordPayload {
  email: string;
}

export interface ResetPasswordPayload {
  new_password: string;
  confirm_password: string;
}

export interface ChangePasswordPayload {
  old_password: string;
  new_password: string;
  confirm_password?: string;
}

// Generate a unique referral code (fallback if backend doesn't provide one)
export function generateReferralCode(): string {
  const prefix = "PROP";
  const suffix = Math.random().toString(36).substring(2, 8).toUpperCase();
  return `${prefix}${suffix}`;
}

export const authApi = {
  // Login (POST /api/accounts/login/) – response: { success, message, data: { access, refresh, user } }
  login: async (payload: LoginPayload): Promise<{ access: string; refresh: string; user?: LoginApiResponse["data"]["user"] }> => {
    const response = await apiClient.post<LoginApiResponse>(ENDPOINTS.auth.login, payload);
    const { data } = response.data;
    return { access: data.access, refresh: data.refresh, user: data.user };
  },

  // Save user to localStorage with 24h expiry (call after login; used to determine auth without /accounts/me)
  saveUserAfterLogin: (user: StoredUser | (Record<string, unknown> & { id: number; email: string })): void => {
    if (typeof window === "undefined") return;
    const expiry = Date.now() + TOKEN_TTL_MS;
    localStorage.setItem(STORAGE_KEY_USER, JSON.stringify(user));
    localStorage.setItem(STORAGE_KEY_EXPIRY, String(expiry));
  },

  // Get stored user if not expired; returns null and clears storage when past 24h
  getStoredUser: (): StoredUser | null => getStoredUserInternal(),

  // Clear user + expiry from storage (call on logout or when session expired)
  clearUserStorage,

  // Register new user (POST /api/accounts/register/)
  signup: async (payload: SignupPayload): Promise<AuthResponse> => {
    // Get referral data if exists (from URL params/localStorage)
    // This is the referrer's code - who referred the current user
    const { code, name, email } = getReferralData();
    
    // Generate referral code for new user if not provided
    // This will be the new user's personal referral code
    const userReferralCode = payload.referral_code || generateReferralCode();
    
    // Build payload with referral data
    const signupPayload: SignupPayload = {
      ...payload,
      username: payload.username || payload.nickname || payload.email.split('@')[0],
      referral_code: userReferralCode,  // User's own referral code
      ...(code && { referred_by: code }), // Referrer's code (if came via referral link)
      ...(name && { referrer_name: name }),
      ...(email && { referrer_email: email }),
    };
    
    const response = await apiClient.post(ENDPOINTS.auth.register, signupPayload);
    
    // Clear referral data after successful signup
    if (response.data) {
      clearReferralData();
    }
    
    return response.data;
  },

  // Refresh access token (POST /api/accounts/token/refresh/)
  refresh: async (refreshToken: string): Promise<{ access: string }> => {
    const response = await apiClient.post(ENDPOINTS.auth.refresh, {
      refresh: refreshToken,
    });
    return response.data;
  },

  // Verify email (POST /api/accounts/verify-email/)
  verifyEmail: async (payload: VerifyEmailPayload): Promise<void> => {
    const response = await apiClient.post(ENDPOINTS.auth.verifyEmail, payload);
    return response.data;
  },

  // Resend verification code (POST /api/accounts/resend-code/)
  resendVerificationCode: async (email: string): Promise<void> => {
    const response = await apiClient.post(ENDPOINTS.auth.resendCode, { email });
    return response.data;
  },

  // Forgot password (POST /api/accounts/forgot-password/)
  forgotPassword: async (payload: ForgotPasswordPayload): Promise<void> => {
    const response = await apiClient.post(ENDPOINTS.auth.forgotPassword, payload);
    return response.data;
  },

  // Reset password (How_it_works.md §16) POST /api/accounts/reset-password/ body: { token, new_password }
  resetPassword: async (
    _uid: string,
    token: string,
    payload: ResetPasswordPayload
  ): Promise<void> => {
    const response = await apiClient.post(ENDPOINTS.auth.resetPassword, {
      token,
      new_password: payload.new_password,
    });
    return response.data;
  },

  // Change password (PUT/PATCH /api/accounts/change-password/)
  changePassword: async (payload: ChangePasswordPayload): Promise<void> => {
    const response = await apiClient.put(ENDPOINTS.auth.changePassword, payload);
    return response.data;
  },

  // Logout – clear cookies (access token 24h), localStorage, and stored user
  logout: async (): Promise<void> => {
    clearUserStorage();
    if (typeof window !== "undefined") {
      const { deleteCookie } = await import("@/lib/cookies");
      deleteCookie("access_token");
      deleteCookie("auth_token");
      deleteCookie("refresh_token");
    }
    localStorage.removeItem("propella_token");
    localStorage.removeItem("access_token");
    localStorage.removeItem("propella_refresh_token");
    localStorage.removeItem("refresh_token");
    localStorage.removeItem("propella_user_id");
  },

  // Sync access token to localStorage (cookie with 24h is set in Login; this is for same-tab reads)
  setToken: (token: string): void => {
    if (typeof window === "undefined") return;
    localStorage.setItem("propella_token", token);
    localStorage.setItem("access_token", token);
  },

  // Helper to set refresh token (sets both names for compatibility)
  setRefreshToken: (token: string): void => {
    localStorage.setItem("propella_refresh_token", token);
    localStorage.setItem("refresh_token", token);
  },

  // Helper to get token (checks cookies first for cross-subdomain, then localStorage)
  getToken: (): string | null => {
    return getAuthTokenFromCookies();
  },

  // Helper to get refresh token (checks cookies first, then localStorage)
  getRefreshToken: (): string | null => {
    // Check cookies first (set by landing page with Domain=.propella.ng)
    const cookieToken = getCookie("refresh_token");
    if (cookieToken) return cookieToken;
    // Fallback to localStorage
    return localStorage.getItem("propella_refresh_token") ||
           localStorage.getItem("refresh_token");
  },

  // Authenticated = valid token + stored user not expired (no /accounts/me call)
  isAuthenticated: (): boolean => {
    return !!(getAuthTokenFromCookies() && getStoredUserInternal());
  },

  // Get current user from storage only (server endpoint /accounts/me not used; 24h expiry applied)
  getMe: async (): Promise<StoredUser | null> => {
    return Promise.resolve(getStoredUserInternal());
  },

  // Edit user (How_it_works.md §8) PUT /accounts/edit-user/
  editUser: async (payload: {
    email?: string;
    first_name?: string;
    last_name?: string;
    nickname?: string;
    [key: string]: unknown;
  }): Promise<{ message: string; user: Record<string, unknown> }> => {
    const response = await apiClient.put(ENDPOINTS.users.editUser, payload);
    return response.data;
  },
};
